/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author srinc
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }
    public void letreroinformacion (String texto) { 
        JOptionPane.showMessageDialog(null, texto);
    }
    public String capturainformacion (String texto) { 
        return (JOptionPane.showInputDialog(texto));
    }
     public int capturainformacionint (String texto) { 
        return Integer.parseInt(JOptionPane.showInputDialog(texto));
    }

    public JButton getBtnconsultarnomina() {
        return btnconsultarnomina;
    }

    public void setBtnconsultarnomina(JButton btnconsultarnomina) {
        this.btnconsultarnomina = btnconsultarnomina;
    }

    public JButton getBtnconsultarprofesor() {
        return btnconsultarprofesor;
    }

    public void setBtnconsultarprofesor(JButton btnconsultarprofesor) {
        this.btnconsultarprofesor = btnconsultarprofesor;
    }

    public JButton getBtninsertardatos() {
        return btninsertardatos;
    }

    public void setBtninsertardatos(JButton btninsertardatos) {
        this.btninsertardatos = btninsertardatos;
    }

    public JButton getBtnnominageneral() {
        return Btnnominageneral;
    }

    public void setBtnnominageneral(JButton Btnnominageneral) {
        this.Btnnominageneral = Btnnominageneral;
    }


    public JComboBox<String> getComboboxestudios() {
        return comboboxestudios;
    }

    public void setComboboxestudios(JComboBox<String> comboboxestudios) {
        this.comboboxestudios = comboboxestudios;
    }

    public JComboBox<String> getComboboxvinculacion() {
        return comboboxvinculacion;
    }

    public void setComboboxvinculacion(JComboBox<String> comboboxvinculacion) {
        this.comboboxvinculacion = comboboxvinculacion;
    }

    public JTextArea getInformacion() {
        return informacion;
    }

    public void setInformacion(JTextArea informacion) {
        this.informacion = informacion;
    }

    public JTextField getTxtcc() {
        return txtcc;
    }

    public void setTxtcc(JTextField txtcc) {
        this.txtcc = txtcc;
    }

    public JTextField getTxthoracatedra() {
        return txthoracatedra;
    }

    public void setTxthoracatedra(JTextField txthoracatedra) {
        this.txthoracatedra = txthoracatedra;
    }

    public JTextField getTxtnombre() {
        return txtnombre;
    }

    public void setTxtnombre(JTextField txtnombre) {
        this.txtnombre = txtnombre;
    }

    public JDialog getCuadroDialogoIngreso() {
        return CuadroDialogoIngreso;
    }

    public void setCuadroDialogoIngreso(JDialog CuadroDialogoIngreso) {
        this.CuadroDialogoIngreso = CuadroDialogoIngreso;
    }

    public JButton getBtningresarAutentificacion() {
        return btningresarAutentificacion;
    }

    public void setBtningresarAutentificacion(JButton btningresarAutentificacion) {
        this.btningresarAutentificacion = btningresarAutentificacion;
    }

    public JButton getBtnsalir() {
        return btnsalir;
    }

    public void setBtnsalir(JButton btnsalir) {
        this.btnsalir = btnsalir;
    }

    public JTextField getTxtpassword() {
        return txtpassword;
    }

    public void setTxtpassword(JTextField txtpassword) {
        this.txtpassword = txtpassword;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CuadroDialogoIngreso = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btningresarAutentificacion = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informacion = new javax.swing.JTextArea();
        comboboxvinculacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboboxestudios = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btninsertardatos = new javax.swing.JButton();
        btnconsultarprofesor = new javax.swing.JButton();
        btnconsultarnomina = new javax.swing.JButton();
        txthoracatedra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Btnnominageneral = new javax.swing.JButton();

        jLabel9.setText("Digite contraseña:");

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        jLabel10.setText("Seleccione su usario");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Profesor", " " }));

        jLabel11.setText(" APP -  NOMINA PROFESOR");

        btningresarAutentificacion.setText("Ingresar");
        btningresarAutentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarAutentificacionActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");

        javax.swing.GroupLayout CuadroDialogoIngresoLayout = new javax.swing.GroupLayout(CuadroDialogoIngreso.getContentPane());
        CuadroDialogoIngreso.getContentPane().setLayout(CuadroDialogoIngresoLayout);
        CuadroDialogoIngresoLayout.setHorizontalGroup(
            CuadroDialogoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroDialogoIngresoLayout.createSequentialGroup()
                .addGroup(CuadroDialogoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuadroDialogoIngresoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(CuadroDialogoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(btningresarAutentificacion))
                        .addGap(43, 43, 43)
                        .addGroup(CuadroDialogoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CuadroDialogoIngresoLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnsalir))))
                    .addGroup(CuadroDialogoIngresoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CuadroDialogoIngresoLayout.setVerticalGroup(
            CuadroDialogoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroDialogoIngresoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(CuadroDialogoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CuadroDialogoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CuadroDialogoIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btningresarAutentificacion)
                    .addComponent(btnsalir))
                .addGap(83, 83, 83))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Universidad Distrital");

        jLabel2.setText("Digite su nombre:");

        jLabel3.setText("Digite su cc:");

        informacion.setColumns(20);
        informacion.setRows(5);
        jScrollPane1.setViewportView(informacion);

        comboboxvinculacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiempo completo", "Medio tiempo", "Hora cátedra", " " }));

        jLabel4.setText("Seleccione su tipo de vinculación:");

        comboboxestudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregrado", "Especialización", "Maestría", "Doctorado", " " }));

        jLabel5.setText("Seleccione su nivel de estudios:");

        btninsertardatos.setText("Insertar Datos");
        btninsertardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertardatosActionPerformed(evt);
            }
        });

        btnconsultarprofesor.setText("Consultar Profesor");

        btnconsultarnomina.setText("Valor Total Nomina");

        jLabel6.setText("Digite sus horas trabajadas:");

        Btnnominageneral.setText("Consulta Nomina General");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre)
                            .addComponent(txtcc)
                            .addComponent(comboboxvinculacion, 0, 258, Short.MAX_VALUE)
                            .addComponent(comboboxestudios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txthoracatedra)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btninsertardatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnconsultarprofesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnconsultarnomina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(Btnnominageneral)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxvinculacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxestudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txthoracatedra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Btnnominageneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btninsertardatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnconsultarprofesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnconsultarnomina)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninsertardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertardatosActionPerformed

    }//GEN-LAST:event_btninsertardatosActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btningresarAutentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarAutentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btningresarAutentificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnnominageneral;
    private javax.swing.JDialog CuadroDialogoIngreso;
    private javax.swing.JButton btnconsultarnomina;
    private javax.swing.JButton btnconsultarprofesor;
    private javax.swing.JButton btningresarAutentificacion;
    private javax.swing.JButton btninsertardatos;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> comboboxestudios;
    private javax.swing.JComboBox<String> comboboxvinculacion;
    private javax.swing.JTextArea informacion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcc;
    private javax.swing.JTextField txthoracatedra;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpassword;
    // End of variables declaration//GEN-END:variables
}
